apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spimmer/argo-test.git
    targetRevision: HEAD
    path: apps/neuvector/charts
    helm:
      releaseName: neuvector
      valueFiles:
      - base/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: neuvector
