---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: init-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: "https://github.com/spimmer/argo-test.git"
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: 'app-config-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/spimmer/argo-test.git"
        targetRevision: HEAD
        path: apps/{{path.basename}}
      destination:
        server: 'https://kubernetes.default.svc'
