apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spimmer/argo-test.git
    targetRevision: HEAD
    path: apps/dummy-pod
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app
